Java02. ДЗ01, Поляков Семен, подгруппа 1
Semionn/au-java-6-course pull request #1
Opened 2016-09-07 13:49 UTC by Semionn

@jzuken
Timofey Bryksin

2016-09-10 18:52 UTC, jzuken commented on src/main/java/com/au/mit/lazy/MultiThreadLazy.java
> +    private volatile LazyResultWrapper<T> wrapper = new NoLazyResult<>();
а точно надо было обёртку делать? обычного бы "дефолтного" объекта не хватило бы для инициализации?

2016-09-10 18:53 UTC, jzuken commented on src/main/java/com/au/mit/lazy/SingleThreadLazy.java
> +    private volatile LazyResultWrapper<T> wrapper = new NoLazyResult<>();
в этой версии volatile, кстати, не особо нужен вроде как

2016-09-10 18:54 UTC, jzuken commented on src/main/java/com/au/mit/lazy/MultiThreadLazy.java
> +    private volatile boolean computed = false;
а зачем нам тут поле, если есть специально выделенное значение NoLazyResult, с которым можно сравниться?

2016-09-11 08:25 UTC, Semionn commented on src/main/java/com/au/mit/lazy/MultiThreadLazy.java
> +    private volatile LazyResultWrapper<T> wrapper = new NoLazyResult<>();
Пожалуй, Null'а тут хватит

2016-09-11 08:25 UTC, Semionn commented on src/main/java/com/au/mit/lazy/MultiThreadLazy.java
> +    private volatile boolean computed = false;
Да, избыточно, написал не подумав)

2016-09-16 11:58 UTC, jzuken commented
хорошо бы ещё и на http://hwproj.me/ сабмит сделать для порядка

2016-09-16 11:59 UTC, jzuken commented on src/main/java/com/au/mit/lazy/LockFreeLazy.java
> +            results.add(new LazyResultWrapper<>(supplier.get()));
раз уж используем синхронизированные списки, предлагаю хотя бы как-то контролировать их размер. а то ну совсем грустно

2016-09-16 12:00 UTC, jzuken requested changes

2016-09-16 15:50 UTC, Semionn commented on src/main/java/com/au/mit/lazy/LockFreeLazy.java
> +            results.add(new LazyResultWrapper<>(supplier.get()));
Не могу придумать, как контролировать размер списка без синхронизации - лучше чем условие пустоты списка не придумать. Переписал lock-free по-другому

2016-09-20 19:44 UTC, jzuken commented on src/main/java/com/au/mit/lazy/LazyResultWrapper.java
> +    private T result;
я бы даже final его ещё сделал

2016-09-20 19:46 UTC, jzuken approved these changes

2016-09-20 19:47 UTC, jzuken commented on src/main/java/com/au/mit/lazy/LockFreeLazy.java
> +            results.add(new LazyResultWrapper<>(supplier.get()));
да, так гораздо лучше

2016-09-20 19:47 UTC, jzuken commented
в принципе, можно мерджить. у меня прав нет

2016-09-26 11:57 UTC, merged